import { MigrationInterface, QueryRunner } from "typeorm";

export class AddSubmissionTables1778408028085 implements MigrationInterface {
    name = 'AddSubmissionTables1778408028085'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "indicator_catalog" DROP CONSTRAINT "indicator_catalog_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "form_templates" DROP CONSTRAINT "form_templates_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "form_templates" DROP CONSTRAINT "form_templates_parent_template_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "form_templates" DROP CONSTRAINT "form_templates_field_category_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicator_org_rules" DROP CONSTRAINT "form_template_indicator_org_rules_indicator_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicator_org_rules" DROP CONSTRAINT "form_template_indicator_org_rules_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicator_org_rules" DROP CONSTRAINT "form_template_indicator_org_rules_template_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" DROP CONSTRAINT "form_template_attributes_parent_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" DROP CONSTRAINT "form_template_attributes_template_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" DROP CONSTRAINT "form_template_indicators_catalog_indicator_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" DROP CONSTRAINT "form_template_indicators_parent_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" DROP CONSTRAINT "form_template_indicators_template_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" DROP CONSTRAINT "form_template_cell_configs_attribute_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" DROP CONSTRAINT "form_template_cell_configs_indicator_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" DROP CONSTRAINT "form_template_cell_configs_template_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" DROP CONSTRAINT "report_submission_cells_updated_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" DROP CONSTRAINT "report_submission_cells_attribute_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" DROP CONSTRAINT "report_submission_cells_indicator_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" DROP CONSTRAINT "report_submission_cells_submission_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "report_campaign_default_values" DROP CONSTRAINT "report_campaign_default_values_attribute_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "report_campaign_default_values" DROP CONSTRAINT "report_campaign_default_values_indicator_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "report_campaign_default_values" DROP CONSTRAINT "report_campaign_default_values_campaign_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "report_assignments" DROP CONSTRAINT "report_assignments_assigned_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "report_assignments" DROP CONSTRAINT "report_assignments_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "report_assignments" DROP CONSTRAINT "report_assignments_template_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "report_assignments" DROP CONSTRAINT "report_assignments_campaign_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "report_campaign_indicator_org_scopes" DROP CONSTRAINT "report_campaign_indicator_org_scopes_indicator_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "report_campaign_indicator_org_scopes" DROP CONSTRAINT "report_campaign_indicator_org_scopes_org_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "report_campaign_indicator_org_scopes" DROP CONSTRAINT "report_campaign_indicator_org_scopes_campaign_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "report_campaigns" DROP CONSTRAINT "report_campaigns_dispatched_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "report_campaigns" DROP CONSTRAINT "report_campaigns_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "report_campaigns" DROP CONSTRAINT "report_campaigns_template_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP CONSTRAINT "FK_organizations_head_user"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP CONSTRAINT "organizations_parent_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "auth_refresh_tokens" DROP CONSTRAINT "auth_refresh_tokens_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "auth_password_resets" DROP CONSTRAINT "auth_password_resets_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "role_permissions_permission_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "role_permissions_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "user_roles_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "user_roles_user_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_users_code"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_templates_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_templates_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_campaign_default_values_campaign"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_report_campaign_scopes_campaign_org"`);
        await queryRunner.query(`DROP INDEX "public"."idx_outbox_status_next_retry"`);
        await queryRunner.query(`DROP INDEX "public"."idx_outbox_aggregate"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_logs_created_at"`);
        await queryRunner.query(`ALTER TABLE "app_outbox_events" DROP CONSTRAINT "chk_outbox_status"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicator_org_rules" DROP CONSTRAINT "UQ_form_template_indicator_org_rules_new"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" DROP CONSTRAINT "UQ_form_template_indicators_template_code"`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" DROP CONSTRAINT "UQ_form_template_cell_configs_key"`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" DROP CONSTRAINT "UQ_report_submission_cells"`);
        await queryRunner.query(`ALTER TABLE "report_assignments" DROP CONSTRAINT "UQ_report_assignments_campaign_org"`);
        await queryRunner.query(`ALTER TABLE "report_campaign_indicator_org_scopes" DROP CONSTRAINT "UQ_report_campaign_scope"`);
        await queryRunner.query(`ALTER TABLE "report_campaigns" DROP CONSTRAINT "UQ_report_campaigns_template_period"`);
        await queryRunner.query(`CREATE TABLE "report_summaries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "form_id" uuid NOT NULL, "period_type" character varying(10) NOT NULL, "period_from" date NOT NULL, "period_to" date NOT NULL, "period_code" character varying(30), "period_name" character varying(255), "org_id" uuid NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'DRAFT', "total_units" integer, "submitted_units" integer, "approved_units" integer, "summary_data" jsonb, "summarized_by" uuid, "summarized_at" TIMESTAMP WITH TIME ZONE, "approved_by" uuid, "approved_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1edffae90dbcf4a67eeb1cd4f5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "report_submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(25) NOT NULL, "assignment_id" uuid NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'DRAFT', "version" integer NOT NULL DEFAULT '1', "note" text, "reject_reason" text, "completion_pct" numeric(5,2), "submitted_by" uuid, "submitted_at" TIMESTAMP WITH TIME ZONE, "approved_by" uuid, "approved_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP DEFAULT now(), CONSTRAINT "UQ_38f7276981fc124b81620f872df" UNIQUE ("code"), CONSTRAINT "PK_8fb46f2835eb89c8fed733eaf9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "department_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatar_url"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "totp_secret"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "totp_enabled"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "notify_channel"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "language"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "timezone"`);
        await queryRunner.query(`ALTER TABLE "form_templates" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "form_templates" DROP COLUMN "template_file"`);
        await queryRunner.query(`ALTER TABLE "form_templates" DROP COLUMN "parent_template_id"`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" DROP COLUMN "data_type"`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" DROP COLUMN "is_required"`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" DROP COLUMN "is_visible"`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" DROP COLUMN "is_readonly"`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" DROP COLUMN "options"`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" DROP COLUMN "validation_rule"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" DROP COLUMN "is_required"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" DROP COLUMN "is_calculated"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" DROP COLUMN "formula"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" DROP COLUMN "group_name"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" DROP COLUMN "min_value"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" DROP COLUMN "max_value"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" DROP COLUMN "validation_rule"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" DROP COLUMN "value"`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" DROP COLUMN "value_numeric"`);
        await queryRunner.query(`ALTER TABLE "report_assignments" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "report_campaign_indicator_org_scopes" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "report_campaigns" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "head_user_id"`);
        await queryRunner.query(`ALTER TABLE "app_outbox_events" DROP COLUMN "next_retry_at"`);
        await queryRunner.query(`ALTER TABLE "app_outbox_events" DROP COLUMN "last_error"`);
        await queryRunner.query(`ALTER TABLE "auth_refresh_tokens" DROP COLUMN "ip_address"`);
        await queryRunner.query(`ALTER TABLE "auth_refresh_tokens" DROP COLUMN "user_agent"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "table_name"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "record_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "old_value"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "new_value"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "ip_address"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "user_agent"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" ADD "value_text" text`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" ADD "value_number" numeric`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entityType" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "entityId" uuid`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "oldValues" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "newValues" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "description" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "ipAddress" inet`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_login"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_login" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "indicator_catalog" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "indicator_catalog" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "field_categories" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "field_categories" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "field_categories" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "field_categories" ADD "updated_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_templates" ALTER COLUMN "period_type" SET DEFAULT 'THANG'`);
        await queryRunner.query(`ALTER TABLE "form_templates" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "form_templates" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_templates" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "form_templates" ADD "updated_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_templates" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "form_templates" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "form_template_indicator_org_rules" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicator_org_rules" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_template_indicator_org_rules" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicator_org_rules" ADD "updated_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" ADD "updated_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "report_campaign_default_values" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "report_campaign_default_values" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "report_campaign_default_values" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "report_campaign_default_values" ADD "updated_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "report_assignments" ALTER COLUMN "campaign_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_assignments" DROP COLUMN "assigned_at"`);
        await queryRunner.query(`ALTER TABLE "report_assignments" ADD "assigned_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "report_campaign_indicator_org_scopes" ALTER COLUMN "source" SET DEFAULT 'CAMPAIGN_OVERRIDE'`);
        await queryRunner.query(`ALTER TABLE "report_campaign_indicator_org_scopes" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "report_campaign_indicator_org_scopes" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "report_campaigns" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "report_campaigns" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "updated_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "app_outbox_events" ALTER COLUMN "aggregate_type" SET DEFAULT 'notification'`);
        await queryRunner.query(`ALTER TABLE "app_outbox_events" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "app_outbox_events" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "auth_refresh_tokens" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auth_password_resets" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "action" character varying(100) NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_13c69424c440a0e765053feb4b" ON "audit_logs" ("entityType", "entityId") `);
        await queryRunner.query(`CREATE INDEX "IDX_99e589da8f9e9326ee0d01a028" ON "audit_logs" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles" ("role_id") `);
        await queryRunner.query(`ALTER TABLE "form_template_indicator_org_rules" ADD CONSTRAINT "UQ_form_template_indicator_org_rules" UNIQUE ("template_id", "org_id", "indicator_id")`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" ADD CONSTRAINT "UQ_form_cell_configs_form_indicator_attribute" UNIQUE ("template_id", "indicator_id", "attribute_id")`);
        await queryRunner.query(`ALTER TABLE "form_templates" ADD CONSTRAINT "FK_b14a05b75ec9862f451295a4ca0" FOREIGN KEY ("field_category_id") REFERENCES "field_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" ADD CONSTRAINT "FK_1570656b4eb3a449190c2cae202" FOREIGN KEY ("template_id") REFERENCES "form_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" ADD CONSTRAINT "FK_1f3477ba1061a648d889c296d45" FOREIGN KEY ("parent_id") REFERENCES "form_template_attributes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" ADD CONSTRAINT "FK_33f32cd9e42b82d215ec641ddce" FOREIGN KEY ("template_id") REFERENCES "form_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" ADD CONSTRAINT "FK_220c10c9e12a2b1a8b81ea33e0d" FOREIGN KEY ("parent_id") REFERENCES "form_template_indicators"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" ADD CONSTRAINT "FK_3a56482ed5efa6da98d19b21d4e" FOREIGN KEY ("template_id") REFERENCES "form_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" ADD CONSTRAINT "FK_5ddab1641b8fd25647abc971070" FOREIGN KEY ("indicator_id") REFERENCES "form_template_indicators"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" ADD CONSTRAINT "FK_3fdd7013791ea2201b0404d9820" FOREIGN KEY ("attribute_id") REFERENCES "form_template_attributes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_campaigns" ADD CONSTRAINT "FK_8d26de0c3b3ae1c3666c4a324e9" FOREIGN KEY ("template_id") REFERENCES "form_templates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD CONSTRAINT "FK_f3a7c9411eaa5f9cbc5363de331" FOREIGN KEY ("parent_id") REFERENCES "organizations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_refresh_tokens" ADD CONSTRAINT "FK_f795ad14f31838e3ddc663ee150" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_password_resets" ADD CONSTRAINT "FK_796e1ecb82d45b6402e65fb8b7f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "auth_password_resets" DROP CONSTRAINT "FK_796e1ecb82d45b6402e65fb8b7f"`);
        await queryRunner.query(`ALTER TABLE "auth_refresh_tokens" DROP CONSTRAINT "FK_f795ad14f31838e3ddc663ee150"`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP CONSTRAINT "FK_f3a7c9411eaa5f9cbc5363de331"`);
        await queryRunner.query(`ALTER TABLE "report_campaigns" DROP CONSTRAINT "FK_8d26de0c3b3ae1c3666c4a324e9"`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" DROP CONSTRAINT "FK_3fdd7013791ea2201b0404d9820"`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" DROP CONSTRAINT "FK_5ddab1641b8fd25647abc971070"`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" DROP CONSTRAINT "FK_3a56482ed5efa6da98d19b21d4e"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" DROP CONSTRAINT "FK_220c10c9e12a2b1a8b81ea33e0d"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" DROP CONSTRAINT "FK_33f32cd9e42b82d215ec641ddce"`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" DROP CONSTRAINT "FK_1f3477ba1061a648d889c296d45"`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" DROP CONSTRAINT "FK_1570656b4eb3a449190c2cae202"`);
        await queryRunner.query(`ALTER TABLE "form_templates" DROP CONSTRAINT "FK_b14a05b75ec9862f451295a4ca0"`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" DROP CONSTRAINT "UQ_form_cell_configs_form_indicator_attribute"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicator_org_rules" DROP CONSTRAINT "UQ_form_template_indicator_org_rules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99e589da8f9e9326ee0d01a028"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13c69424c440a0e765053feb4b"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "action"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "action" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auth_password_resets" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auth_refresh_tokens" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "app_outbox_events" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "app_outbox_events" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_outbox_events" ALTER COLUMN "aggregate_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "updated_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "organizations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "report_campaigns" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "report_campaigns" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "report_campaign_indicator_org_scopes" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "report_campaign_indicator_org_scopes" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "report_campaign_indicator_org_scopes" ALTER COLUMN "source" SET DEFAULT 'MANUAL'`);
        await queryRunner.query(`ALTER TABLE "report_assignments" DROP COLUMN "assigned_at"`);
        await queryRunner.query(`ALTER TABLE "report_assignments" ADD "assigned_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "report_assignments" ALTER COLUMN "campaign_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "report_campaign_default_values" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "report_campaign_default_values" ADD "updated_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "report_campaign_default_values" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "report_campaign_default_values" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" ADD "updated_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_template_indicator_org_rules" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicator_org_rules" ADD "updated_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "form_template_indicator_org_rules" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "form_template_indicator_org_rules" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_templates" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "form_templates" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "form_templates" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "form_templates" ADD "updated_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "form_templates" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "form_templates" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "form_templates" ALTER COLUMN "period_type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "field_categories" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "field_categories" ADD "updated_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "field_categories" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "field_categories" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "indicator_catalog" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "indicator_catalog" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_login"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_login" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "ipAddress"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "newValues"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "oldValues"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entityId"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "entityType"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" DROP COLUMN "value_number"`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" DROP COLUMN "value_text"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "user_agent" text`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "ip_address" character varying(45)`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "new_value" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "old_value" jsonb`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "record_id" bigint`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "table_name" character varying(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "auth_refresh_tokens" ADD "user_agent" text`);
        await queryRunner.query(`ALTER TABLE "auth_refresh_tokens" ADD "ip_address" character varying(45)`);
        await queryRunner.query(`ALTER TABLE "app_outbox_events" ADD "last_error" text`);
        await queryRunner.query(`ALTER TABLE "app_outbox_events" ADD "next_retry_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD "head_user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "report_campaigns" ADD "updated_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "report_campaign_indicator_org_scopes" ADD "updated_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "report_assignments" ADD "status" character varying(20) NOT NULL DEFAULT 'ASSIGNED'`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" ADD "value_numeric" numeric`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" ADD "value" text`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" ADD "validation_rule" jsonb`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" ADD "max_value" numeric`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" ADD "min_value" numeric`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" ADD "group_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" ADD "formula" text`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" ADD "is_calculated" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" ADD "is_required" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" ADD "validation_rule" jsonb`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" ADD "options" jsonb`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" ADD "is_readonly" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" ADD "is_visible" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" ADD "is_required" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" ADD "data_type" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "form_templates" ADD "parent_template_id" uuid`);
        await queryRunner.query(`ALTER TABLE "form_templates" ADD "template_file" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "form_templates" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "users" ADD "timezone" character varying(50) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "language" character varying(10) NOT NULL DEFAULT 'vi'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "notify_channel" character varying(20) NOT NULL DEFAULT 'both'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "totp_enabled" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" ADD "totp_secret" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatar_url" text`);
        await queryRunner.query(`ALTER TABLE "users" ADD "department_id" uuid`);
        await queryRunner.query(`DROP TABLE "report_submissions"`);
        await queryRunner.query(`DROP TABLE "report_summaries"`);
        await queryRunner.query(`ALTER TABLE "report_campaigns" ADD CONSTRAINT "UQ_report_campaigns_template_period" UNIQUE ("template_id", "period_type", "period_code")`);
        await queryRunner.query(`ALTER TABLE "report_campaign_indicator_org_scopes" ADD CONSTRAINT "UQ_report_campaign_scope" UNIQUE ("campaign_id", "org_id", "indicator_id")`);
        await queryRunner.query(`ALTER TABLE "report_assignments" ADD CONSTRAINT "UQ_report_assignments_campaign_org" UNIQUE ("campaign_id", "org_id")`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" ADD CONSTRAINT "UQ_report_submission_cells" UNIQUE ("submission_id", "indicator_id", "attribute_id")`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" ADD CONSTRAINT "UQ_form_template_cell_configs_key" UNIQUE ("template_id", "indicator_id", "attribute_id")`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" ADD CONSTRAINT "UQ_form_template_indicators_template_code" UNIQUE ("template_id", "code")`);
        await queryRunner.query(`ALTER TABLE "form_template_indicator_org_rules" ADD CONSTRAINT "UQ_form_template_indicator_org_rules_new" UNIQUE ("template_id", "org_id", "indicator_id")`);
        await queryRunner.query(`ALTER TABLE "app_outbox_events" ADD CONSTRAINT "chk_outbox_status" CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'PROCESSED'::character varying, 'FAILED'::character varying])::text[])))`);
        await queryRunner.query(`CREATE INDEX "IDX_audit_logs_created_at" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_outbox_aggregate" ON "app_outbox_events" ("aggregate_id", "aggregate_type", "created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_outbox_status_next_retry" ON "app_outbox_events" ("next_retry_at", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_report_campaign_scopes_campaign_org" ON "report_campaign_indicator_org_scopes" ("campaign_id", "org_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_campaign_default_values_campaign" ON "report_campaign_default_values" ("campaign_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_templates_type" ON "form_templates" ("template_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_templates_status" ON "form_templates" ("template_status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_users_code" ON "users" ("code") WHERE (code IS NOT NULL)`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_password_resets" ADD CONSTRAINT "auth_password_resets_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_refresh_tokens" ADD CONSTRAINT "auth_refresh_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD CONSTRAINT "organizations_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organizations" ADD CONSTRAINT "FK_organizations_head_user" FOREIGN KEY ("head_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_campaigns" ADD CONSTRAINT "report_campaigns_template_id_fkey" FOREIGN KEY ("template_id") REFERENCES "form_templates"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_campaigns" ADD CONSTRAINT "report_campaigns_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_campaigns" ADD CONSTRAINT "report_campaigns_dispatched_by_fkey" FOREIGN KEY ("dispatched_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_campaign_indicator_org_scopes" ADD CONSTRAINT "report_campaign_indicator_org_scopes_campaign_id_fkey" FOREIGN KEY ("campaign_id") REFERENCES "report_campaigns"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_campaign_indicator_org_scopes" ADD CONSTRAINT "report_campaign_indicator_org_scopes_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_campaign_indicator_org_scopes" ADD CONSTRAINT "report_campaign_indicator_org_scopes_indicator_id_fkey" FOREIGN KEY ("indicator_id") REFERENCES "form_template_indicators"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_assignments" ADD CONSTRAINT "report_assignments_campaign_id_fkey" FOREIGN KEY ("campaign_id") REFERENCES "report_campaigns"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_assignments" ADD CONSTRAINT "report_assignments_template_id_fkey" FOREIGN KEY ("template_id") REFERENCES "form_templates"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_assignments" ADD CONSTRAINT "report_assignments_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_assignments" ADD CONSTRAINT "report_assignments_assigned_by_fkey" FOREIGN KEY ("assigned_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_campaign_default_values" ADD CONSTRAINT "report_campaign_default_values_campaign_id_fkey" FOREIGN KEY ("campaign_id") REFERENCES "report_campaigns"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_campaign_default_values" ADD CONSTRAINT "report_campaign_default_values_indicator_id_fkey" FOREIGN KEY ("indicator_id") REFERENCES "form_template_indicators"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_campaign_default_values" ADD CONSTRAINT "report_campaign_default_values_attribute_id_fkey" FOREIGN KEY ("attribute_id") REFERENCES "form_template_attributes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" ADD CONSTRAINT "report_submission_cells_submission_id_fkey" FOREIGN KEY ("submission_id") REFERENCES "report_submissions_new"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" ADD CONSTRAINT "report_submission_cells_indicator_id_fkey" FOREIGN KEY ("indicator_id") REFERENCES "form_template_indicators"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" ADD CONSTRAINT "report_submission_cells_attribute_id_fkey" FOREIGN KEY ("attribute_id") REFERENCES "form_template_attributes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "report_submission_cells" ADD CONSTRAINT "report_submission_cells_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" ADD CONSTRAINT "form_template_cell_configs_template_id_fkey" FOREIGN KEY ("template_id") REFERENCES "form_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" ADD CONSTRAINT "form_template_cell_configs_indicator_id_fkey" FOREIGN KEY ("indicator_id") REFERENCES "form_template_indicators"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template_cell_configs" ADD CONSTRAINT "form_template_cell_configs_attribute_id_fkey" FOREIGN KEY ("attribute_id") REFERENCES "form_template_attributes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" ADD CONSTRAINT "form_template_indicators_template_id_fkey" FOREIGN KEY ("template_id") REFERENCES "form_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" ADD CONSTRAINT "form_template_indicators_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "form_template_indicators"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template_indicators" ADD CONSTRAINT "form_template_indicators_catalog_indicator_id_fkey" FOREIGN KEY ("catalog_indicator_id") REFERENCES "indicator_catalog"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" ADD CONSTRAINT "form_template_attributes_template_id_fkey" FOREIGN KEY ("template_id") REFERENCES "form_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template_attributes" ADD CONSTRAINT "form_template_attributes_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "form_template_attributes"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template_indicator_org_rules" ADD CONSTRAINT "form_template_indicator_org_rules_template_id_fkey" FOREIGN KEY ("template_id") REFERENCES "form_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template_indicator_org_rules" ADD CONSTRAINT "form_template_indicator_org_rules_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_template_indicator_org_rules" ADD CONSTRAINT "form_template_indicator_org_rules_indicator_id_fkey" FOREIGN KEY ("indicator_id") REFERENCES "form_template_indicators"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_templates" ADD CONSTRAINT "form_templates_field_category_id_fkey" FOREIGN KEY ("field_category_id") REFERENCES "field_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_templates" ADD CONSTRAINT "form_templates_parent_template_id_fkey" FOREIGN KEY ("parent_template_id") REFERENCES "form_templates"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_templates" ADD CONSTRAINT "form_templates_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "indicator_catalog" ADD CONSTRAINT "indicator_catalog_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
