export enum ReportStatus {
  DRAFT = 'DRAFT',
  ASSIGNED = 'ASSIGNED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ReportAssignmentStatus {
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ReportActionType {
  CREATE_REPORT = 'CREATE_REPORT',
  UPDATE_REPORT_INFO = 'UPDATE_REPORT_INFO',
  CONFIG_ASSIGNMENT_SCOPE = 'CONFIG_ASSIGNMENT_SCOPE',
  PUBLISH_REPORT = 'PUBLISH_REPORT',
  SAVE_ASSIGNMENT_DRAFT = 'SAVE_ASSIGNMENT_DRAFT',
  SUBMIT_ASSIGNMENT = 'SUBMIT_ASSIGNMENT',
  APPROVE_ASSIGNMENT = 'APPROVE_ASSIGNMENT',
  REJECT_ASSIGNMENT = 'REJECT_ASSIGNMENT',
  CANCEL_REPORT = 'CANCEL_REPORT',
}
